Functions

1.Define the function

2.Invoking the functions

3.Passing the arguments

In [3]:
def cake_baker(p,f,s):
  print("No of pieces:",p)
  print("Flavour:",f)
  print("order size:",s)
cake_baker("5","Chocolate","3kg")
cake_baker("25","Vanilla","5kg")

No of pieces: 5
Flavour: Chocolate
order size: 3kg
No of pieces: 25
Flavour: Vanilla
order size: 5kg


In [5]:
def add(*args):
  sum=0
  for i in args:
    sum=sum+i
  return sum
print(add(1,2,9))

12


In [9]:
def greet(**kwargs):
  print("hello")
  for key, value in kwargs.items():
    print(value, end=" ")

greet(name="pranav",usn="01fe21bec025",branch="ECE")

hello
pranav 01fe21bec025 ECE 

In [13]:
import random
x=random.randint(1,9)
print(x)

a=random.random()
print(a)

1
0.31080457831727726


In [15]:
import random
computer=random.randint(1,9)
userinput=int(input("Enter the number between 1 and 9"))
print(computer)
print(userinput)

if computer>userinput:
  print("Computer won")
elif computer==userinput:
  print("TIE")
else:
  print("you won")

Enter the number between 1 and 94
8
4
Computer won


In [18]:
import random
gamelist=['rock','paper','scissor']
z=random.choice(gamelist)
user=input("Enter the choice")
print(z)
print(user)

if z==user:
  print("TIE")
elif (z=="rock" and user=="paper"):
  print("computer won")
elif(z=="paper" and user=="scissor"):
  print("user won")
elif(z=="scissor" and user=="paper"):
  print("computer won")

Enter the choicepaper
rock
paper
computer won


NumPy-Numerical Python

Limitation: It cannot handle non homogenous data

In [19]:
import numpy as np

In [22]:
a=np.array([35,1,36,45,78,23])
print(type(a))

b=np.zeros(3)
c=np.ones(4)
print(b)
print(c)

d=np.sort(a)
print(d)

<class 'numpy.ndarray'>
[0. 0. 0.]
[1. 1. 1. 1.]
[ 1 23 35 36 45 78]
